//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissingNumbers.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MissingNumbersMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MissingNumbersMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissingNumbers.Utilities.Resources.MissingNumbersMessages", typeof(MissingNumbersMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El segundo arreglo debe ser mayor que el primero.
        /// </summary>
        public static string ErrorArraysLength {
            get {
                return ResourceManager.GetString("ErrorArraysLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error convirtiendo los números..
        /// </summary>
        public static string ErrorConvertingNumbers {
            get {
                return ResourceManager.GetString("ErrorConvertingNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del primer arreglo debe ser mayor a 1.
        /// </summary>
        public static string ErrorLengthFirstArray {
            get {
                return ResourceManager.GetString("ErrorLengthFirstArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La diferencia entre los numeros del segundo arreglo es mayor a 100.
        /// </summary>
        public static string ErrorSecondArrayDifferenceNunmberGreater100 {
            get {
                return ResourceManager.GetString("ErrorSecondArrayDifferenceNunmberGreater100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud del segundo arreglo demasiado grande.
        /// </summary>
        public static string ErrorSecondArrayGreat {
            get {
                return ResourceManager.GetString("ErrorSecondArrayGreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los números del segundo arreglo están fuera del rango.
        /// </summary>
        public static string ErrorSecondArrayNumbersOutOfRange {
            get {
                return ResourceManager.GetString("ErrorSecondArrayNumbersOutOfRange", resourceCulture);
            }
        }
    }
}
